plot(as.dendrogram(hc))
abline(h = 1.5 , col="blue")
abline(h = .4 , col="red")
abline(h = 0.05 , col="green")
heatmap(dataMatrix, col = cm.colors(25))
heatmap(mt)
plot(denmt)
points(cx, cy , col = c("red","orange","purple") , pch = 3, cex = 2 , lwd = 2)
mdist(x, y, cx, cy )
apply(distTmp , 2, which.min)
points(x,y, pch = 19, cex = 2 , col = cols1[newClust])
tapply(x, newClust , mean )
tapply(y, newClust , mean )
points(newCx,newCy, col = cols1 , pch = 8, cex = 2 , lwd = 2)
mdist(x, y . newCx, newCy)
mdist(x, y , newCx, newCy)
apply(distTmp2, 2, which.min)
points(x, y, pch = 19, cex = 2, col = cols1[newClust2])
tapply(y, newClust2 , mean )
tapply(x, newClust2 , mean )
points(finalCx,finalCy, col = cols1 , pch = 9, cex = 2 , lwd = 2)
kmeans(dataFrame, centers = 3)
kmObj$iter
plot(x, y , col = kmObj$cluster , pch = 19, cex = 2)
points(kmObj$centers , col = c("black","red","green"), pch = 3, cex = 3, lwd = 3)
plot(x, y , col = kmeans(dataFrame, 6)$cluster , pch = 19, cex = 2)
points(kmObj$centers , col = c("black","red","green"), pch = 3, cex = 3, lwd = 3)
plot(x, y , col = kmeans(dataFrame, 6)$cluster , pch = 19, cex = 2)
heatmap(dataMatrix)
myedit("addPatt.R")
set.seed(678910)
for(i in 1:40){
  # flip a coin
  coinFlip <- rbinom(1,size=1,prob=0.5)
  # if coin is heads add a common pattern to that row
  if(coinFlip){
    dataMatrix[i,] <- dataMatrix[i,] + rep(c(0,3),each=5)
  }
}source("addPatt.R", local = TRUE)
heatmap(dataMatrix)
svd(mat)
matu %*% diag %*% t(matv)
svd(scale(mat))
prcomp(scale(mat))
svd1 < svd(dataMatrix)

a2 <- svd1$u[,c(1,2)] %*% svd1$d[c(1,2)] %*% t(svd1$v[,1])
myImage(a2)
myImage(svd1$u[,1:5] %*% diag(svd1$d[1:5]) %*% t(svd1$v[,1:5]))
myImage(svd1$u[,1:10] %*% diag(svd1$d[1:10]) %*% t(svd1$v[,1:10]))

#showXY.R
par(mfrow=c(1, 2), mar = c(5, 4, 1, 1))
plot(sub1[, 1], col = sub1$activity, ylab = names(sub1)[1])
plot(sub1[, 2], col = sub1$activity, ylab = names(sub1)[2])
legend("bottomright",legend=unique(sub1$activity),col=unique(sub1$activity), pch = 1)
par(mfrow=c(1,1))
showMe(1:6)
mdist <- dist(sub1[,1:3])
hclustering <- hclust(mdist)
myplclust(hclustering , lab.col =  unclass(sub1$activity))
mdist <- dist(sub1[,10:12])
hclustering <- hclust(mdist)
myplclust(hclustering , lab.col =  unclass(sub1$activity))
svd1 <- svd(scale(sub1[,-c(562,563)]))
maxCon <- which.max(svd1$v[,2])
mdist <- dist(sub1[,c(10:12,maxCon)])
hclustering <- hclust(mdist)
myplclust(hclustering , lab.col =  unclass(sub1$activity))
kClust <- kmeans(sub1[, -c(562,563)] , centers = 6)
table(kClust$cluster, sub1$activity)
kClust <- kmeans(sub1[, -c(562,563)] , centers = 6 , nstart = 100)
table(kClust$cluster, sub1$activity)
dim(kClust$centers)
laying <- which(kClust$size == 29)
plot(kClust$centers[laying,1:12], pch = 19, ylab="Laying Cluster")
names(sub1[,1:3])
walkdown <- which(kClust$size == 49)
plot(kClust$centers[walkdown,1:12], pch = 19, ylab="Walkdown Cluster")
