---
title: "LeafletDemo"
author: "Trina Dey"
date: "03/01/2021"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Leaflet First Map
```{r ,echo=TRUE}
library(leaflet)
my_map <- leaflet() %>% addTiles()
my_map
```

## Adding markers
```{r, echo=TRUE}
my_map <- my_map %>% addMarkers(lat = 39.2980803, lng = -76.5898801, popup = "Jeff's Office")
my_map
```

## Adding multiple markers
```{r}
set.seed(11111)
df <- data.frame(lat = runif(20, min = 39.2, max = 39.3),lng = runif(20, min = -76.6, max = -76.5))
df %>% leaflet() %>% addTiles() %>% addMarkers()
```

## Adding self created markers
```{r, echo =FALSE}
hopkinsIcon <- makeIcon(
    iconUrl = "https://www.gstatic.com/recaptcha/api2/logo_48.png",
    iconWidth = 31*215/230, iconHeight = 31,
    iconAnchorX = 31*215/230/2, iconAnchorY = 16
)

hopkinsLatLng <- data.frame(
    lat = c(39.2973166, 39.3288851,39.2906617, 39.2970681, 39.2824806),
    lng = c(-76.5929798, -76.6206598, -76.5469683, -76.6150537, -76.6016766)
)
hopkinsLatLng %>% leaflet() %>% addTiles() %>% addMarkers(icon = hopkinsIcon)

```

## Adding different hovers for each marker
```{r, echo = FALSE}
hopkinsSites <- c(
    "<a href='https://www.google.com'>Google</a>",
    "<a href='https://www.gmail.com'>Gmail</a>",
    "<a href='https://facebook.com'>Facebook</a>",
    "<a href='https://www.instagram.com'>Instagram</a>",
    "<a href='https://drive.google.com'>Google Drive</a>"
)
hopkinsLatLng %>% leaflet() %>% addTiles() %>% addMarkers(icon = hopkinsIcon,popup = hopkinsSites)

```

## Mapping clusters
sometimes there is a cluster of markers and it doesnt make sense to plot all the markers. So we use clusterOptions
```{r, echo=FALSE}
set.seed(11111)
df <- data.frame(lat = runif(500, min = 39.2, max = 39.3),lng = runif(500, min = -76.6, max = -76.5))
df %>% leaflet() %>% addTiles() %>% addMarkers(clusterOptions = markerClusterOptions())
```


## Mapping Circle Clusters
```{r, echo = FALSE}
set.seed(11111)
df <- data.frame(lat = runif(20, min = 39.2, max = 39.3),lng = runif(20, min = -76.6, max = -76.5))
df %>% leaflet() %>% addTiles() %>% addCircleMarkers()
```


## Drawing Circles
```{r, echo = FALSE}
hopkinsLatLng <- data.frame(
    lat = c(39.2973166, 39.3288851,39.2906617, 39.2970681, 39.2824806),
    lng = c(-76.5929798, -76.6206598, -76.5469683, -76.6150537, -76.6016766)
)
hopkinsLatLng %>% leaflet() %>% addTiles() %>% addCircles(weight = 10, radius = c(5,10,15,20,25)*30)
```

## Drawing Rectangles
```{r, echo = FALSE}
 leaflet() %>% addTiles() %>% addRectangles(lat1 = 37.2588, lng1= -122.0595, lat2 = 37.2590, lng2 = -122.0625)
```

## Adding legends
```{r, echo = FALSE}
df <- data.frame(lat = runif(20, min = 39.2, max = 39.3),lng = runif(20, min = -76.6, max = -76.5),
                 col=sample(c("red","blue","green"),20, replace=TRUE),stringsAsFactors = TRUE)
df %>% leaflet() %>% addTiles() %>% addCircleMarkers(color  = df$col) %>% 
    addLegend(labels = LETTERS[1:3], colors = c("red","blue","green"))
```














